/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prfinal.grammys;
import java.util.ArrayList;
/**
 *
 * @author esepatojo
 */
public class prgrammys extends javax.swing.JFrame {
    ArrayList <data>cofre=new ArrayList();
    /**
     * Creates new form prgrammys
     */
    public prgrammys() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondogrammy = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        artistan5 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        artistan10 = new javax.swing.JToggleButton();
        artistan2 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        artistan3 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        artistan4 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        muestradt = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        artistan1 = new javax.swing.JToggleButton();
        artistan6 = new javax.swing.JToggleButton();
        artistan7 = new javax.swing.JToggleButton();
        artistan8 = new javax.swing.JToggleButton();
        artistan9 = new javax.swing.JToggleButton();
        eliminar = new javax.swing.JToggleButton();
        mostrar = new javax.swing.JToggleButton();
        salir = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondogrammy.setIcon(new javax.swing.ImageIcon("C:\\Users\\esepatojo\\Desktop\\gras.png")); // NOI18N
        getContentPane().add(fondogrammy, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, -10, 400, 300));

        jLabel1.setText("NO.2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 30, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("¡Nominaciones Artistas Latinos!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 330, 20));

        jLabel3.setText("NO.5");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 30, 20));

        artistan5.setText("Camila Cabello");
        artistan5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistan5ActionPerformed(evt);
            }
        });
        getContentPane().add(artistan5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 105, -1));

        jLabel4.setText("NO.10");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 40, 20));

        artistan10.setText("Nicky Jam");
        artistan10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistan10ActionPerformed(evt);
            }
        });
        getContentPane().add(artistan10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 105, -1));

        artistan2.setText("Bad Bunny");
        artistan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistan2ActionPerformed(evt);
            }
        });
        getContentPane().add(artistan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 105, -1));

        jLabel5.setText("NO.3");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 30, 20));

        artistan3.setText("Ozuna");
        artistan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistan3ActionPerformed(evt);
            }
        });
        getContentPane().add(artistan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 105, -1));

        jLabel6.setText("NO.4");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 30, 20));

        artistan4.setText("Daddy Yankee");
        artistan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistan4ActionPerformed(evt);
            }
        });
        getContentPane().add(artistan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 105, -1));

        muestradt.setColumns(20);
        muestradt.setRows(5);
        jScrollPane1.setViewportView(muestradt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 270, -1));

        jLabel7.setText("NO.1");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 30, 20));

        jLabel8.setText("NO.6");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 30, 20));

        jLabel9.setText("NO.7");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 30, 20));

        jLabel10.setText("NO.8");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 30, 20));

        jLabel11.setText("NO.9");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 30, 20));

        artistan1.setText("J Balvin");
        artistan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistan1ActionPerformed(evt);
            }
        });
        getContentPane().add(artistan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 105, -1));

        artistan6.setText("Maluma");
        artistan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistan6ActionPerformed(evt);
            }
        });
        getContentPane().add(artistan6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 105, -1));

        artistan7.setText("Anuel AA");
        artistan7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistan7ActionPerformed(evt);
            }
        });
        getContentPane().add(artistan7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 105, -1));

        artistan8.setText("Karol G");
        artistan8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistan8ActionPerformed(evt);
            }
        });
        getContentPane().add(artistan8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 105, -1));

        artistan9.setText("Shakira");
        artistan9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistan9ActionPerformed(evt);
            }
        });
        getContentPane().add(artistan9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 105, -1));

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 110, 30));

        mostrar.setText("Mostrar");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 110, 30));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void artistan9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistan9ActionPerformed
     cofre.add( new data("Shakira") );
        // TODO add your handling code here:
    }//GEN-LAST:event_artistan9ActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
    cofre.clear();
    muestradt.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarActionPerformed

    private void artistan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistan1ActionPerformed
     cofre.add( new data("J Balvin") );
        // TODO add your handling code here:
    }//GEN-LAST:event_artistan1ActionPerformed

    private void artistan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistan2ActionPerformed
     cofre.add( new data("Bad Bunny") );
        // TODO add your handling code here:
    }//GEN-LAST:event_artistan2ActionPerformed

    private void artistan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistan3ActionPerformed
     cofre.add( new data("Ozuna") );
        // TODO add your handling code here:
    }//GEN-LAST:event_artistan3ActionPerformed

    private void artistan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistan4ActionPerformed
     cofre.add( new data("Daddy Yankee") );
        // TODO add your handling code here:
    }//GEN-LAST:event_artistan4ActionPerformed

    private void artistan5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistan5ActionPerformed
     cofre.add( new data("Camila Cabello") );
        // TODO add your handling code here:
    }//GEN-LAST:event_artistan5ActionPerformed

    private void artistan6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistan6ActionPerformed
     cofre.add( new data("Maluma") );
        // TODO add your handling code here:
    }//GEN-LAST:event_artistan6ActionPerformed

    private void artistan7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistan7ActionPerformed
     cofre.add( new data("Anuel AA") );
        // TODO add your handling code here:
    }//GEN-LAST:event_artistan7ActionPerformed

    private void artistan8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistan8ActionPerformed
     cofre.add( new data("Karol G") );
        // TODO add your handling code here:
    }//GEN-LAST:event_artistan8ActionPerformed

    private void artistan10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistan10ActionPerformed
     cofre.add( new data("Nicky Jam") );
        // TODO add your handling code here:
    }//GEN-LAST:event_artistan10ActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
         int n = cofre.size();
        data tmp=null;
        muestradt.setText("");
        for(int i=0;i<=(n-1);i++)
        {
            tmp = cofre.get(i);
            muestradt.append("Artista: "+tmp.getartista()+"\n\r");
        }       
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
    dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prgrammys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prgrammys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prgrammys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prgrammys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prgrammys().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton artistan1;
    private javax.swing.JToggleButton artistan10;
    private javax.swing.JToggleButton artistan2;
    private javax.swing.JToggleButton artistan3;
    private javax.swing.JToggleButton artistan4;
    private javax.swing.JToggleButton artistan5;
    private javax.swing.JToggleButton artistan6;
    private javax.swing.JToggleButton artistan7;
    private javax.swing.JToggleButton artistan8;
    private javax.swing.JToggleButton artistan9;
    private javax.swing.JToggleButton eliminar;
    private javax.swing.JLabel fondogrammy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton mostrar;
    private javax.swing.JTextArea muestradt;
    private javax.swing.JToggleButton salir;
    // End of variables declaration//GEN-END:variables
}
